/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.manageTrucksView;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EVEN
 */
public class ManageTrucksFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageTrucksFrame.class.getName());

    /**
     * Creates new form ManageTrucksFrame
     */
    public ManageTrucksFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageTrucksLabel = new javax.swing.JLabel();
        manageTrucksTabbedPane = new javax.swing.JTabbedPane();
        addStoreJPanel = new javax.swing.JPanel();
        truckNameLabel = new javax.swing.JLabel();
        truckDescriptionLabel = new javax.swing.JLabel();
        clearTextButton = new javax.swing.JButton();
        addTruckButton = new javax.swing.JButton();
        addTruckBackButton = new javax.swing.JButton();
        truckNameTextField = new javax.swing.JTextField();
        addTruckScrollPane = new javax.swing.JScrollPane();
        truckDescriptionTextArea = new javax.swing.JTextArea();
        editStoresJPanel = new javax.swing.JPanel();
        editStoresScrollPane = new javax.swing.JScrollPane();
        editTrucksTable = new javax.swing.JTable();
        editTruckButton = new javax.swing.JButton();
        deleteTruckButton = new javax.swing.JButton();
        editTrucksBackButton = new javax.swing.JButton();
        asignEmployeesPanel = new javax.swing.JPanel();
        selectTruckLabel = new javax.swing.JLabel();
        selectEmployeeLabel = new javax.swing.JLabel();
        selectEmployeeComboBox = new javax.swing.JComboBox<>();
        selectTruckComboBox = new javax.swing.JComboBox<>();
        assignEmployeeButton = new javax.swing.JButton();
        assignEmployeesBackButton = new javax.swing.JButton();
        manageAsignedEmployeesPanel = new javax.swing.JPanel();
        maeSelectTruckLabel = new javax.swing.JLabel();
        manageAssignedEmployeesScrollPane = new javax.swing.JScrollPane();
        manageAssignedEmployeesTable = new javax.swing.JTable();
        maeSelectTruckComboBox = new javax.swing.JComboBox<>();
        showAssignedEmployeesButton = new javax.swing.JButton();
        unassignEmployeeButton = new javax.swing.JButton();
        manageAssignedEmployeesBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageTrucksLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageTrucksLabel.setText("Manage Trucks");

        manageTrucksTabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        truckNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        truckNameLabel.setText("Truck Name / License Plate:");

        truckDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        truckDescriptionLabel.setText("Truck Description:");

        clearTextButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearTextButton.setText("Clear Text");

        addTruckButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addTruckButton.setText("Add Truck");

        addTruckBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addTruckBackButton.setText("Back");

        truckNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        truckDescriptionTextArea.setColumns(20);
        truckDescriptionTextArea.setRows(5);
        addTruckScrollPane.setViewportView(truckDescriptionTextArea);

        javax.swing.GroupLayout addStoreJPanelLayout = new javax.swing.GroupLayout(addStoreJPanel);
        addStoreJPanel.setLayout(addStoreJPanelLayout);
        addStoreJPanelLayout.setHorizontalGroup(
            addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStoreJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStoreJPanelLayout.createSequentialGroup()
                        .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addTruckBackButton)
                            .addComponent(truckNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                        .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addStoreJPanelLayout.createSequentialGroup()
                                .addComponent(clearTextButton)
                                .addGap(18, 18, 18)
                                .addComponent(addTruckButton))
                            .addComponent(truckNameTextField)))
                    .addGroup(addStoreJPanelLayout.createSequentialGroup()
                        .addComponent(truckDescriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addTruckScrollPane)))
                .addContainerGap())
        );
        addStoreJPanelLayout.setVerticalGroup(
            addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStoreJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(truckNameLabel)
                    .addComponent(truckNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStoreJPanelLayout.createSequentialGroup()
                        .addComponent(truckDescriptionLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(addTruckScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearTextButton)
                    .addComponent(addTruckButton)
                    .addComponent(addTruckBackButton))
                .addContainerGap())
        );

        manageTrucksTabbedPane.addTab("Add Truck", addStoreJPanel);

        editTrucksTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editTrucksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Truck ID", "Name/License Plate", "Truck Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        editStoresScrollPane.setViewportView(editTrucksTable);

        editTruckButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editTruckButton.setText("Edit Truck");

        deleteTruckButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteTruckButton.setText("Delete Truck");

        editTrucksBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editTrucksBackButton.setText("Back");

        javax.swing.GroupLayout editStoresJPanelLayout = new javax.swing.GroupLayout(editStoresJPanel);
        editStoresJPanel.setLayout(editStoresJPanelLayout);
        editStoresJPanelLayout.setHorizontalGroup(
            editStoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStoresJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editStoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editStoresScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editStoresJPanelLayout.createSequentialGroup()
                        .addComponent(editTrucksBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteTruckButton)
                        .addGap(18, 18, 18)
                        .addComponent(editTruckButton)))
                .addContainerGap())
        );
        editStoresJPanelLayout.setVerticalGroup(
            editStoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStoresJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editStoresScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(editStoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editTruckButton)
                    .addComponent(deleteTruckButton)
                    .addComponent(editTrucksBackButton))
                .addContainerGap())
        );

        manageTrucksTabbedPane.addTab("Edit Truck", editStoresJPanel);

        selectTruckLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectTruckLabel.setText("Select Truck:");

        selectEmployeeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectEmployeeLabel.setText("Select Employee:");

        selectEmployeeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectEmployeeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectTruckComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectTruckComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        assignEmployeeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        assignEmployeeButton.setText("Assign Employee");

        assignEmployeesBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        assignEmployeesBackButton.setText("Back");

        javax.swing.GroupLayout asignEmployeesPanelLayout = new javax.swing.GroupLayout(asignEmployeesPanel);
        asignEmployeesPanel.setLayout(asignEmployeesPanelLayout);
        asignEmployeesPanelLayout.setHorizontalGroup(
            asignEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignEmployeesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asignEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(asignEmployeesPanelLayout.createSequentialGroup()
                        .addComponent(selectTruckLabel)
                        .addGap(18, 18, 18)
                        .addComponent(selectTruckComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectEmployeeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectEmployeeComboBox, 0, 226, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, asignEmployeesPanelLayout.createSequentialGroup()
                        .addComponent(assignEmployeesBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(assignEmployeeButton)))
                .addContainerGap())
        );
        asignEmployeesPanelLayout.setVerticalGroup(
            asignEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asignEmployeesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asignEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectTruckLabel)
                    .addComponent(selectEmployeeLabel)
                    .addComponent(selectEmployeeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectTruckComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addGroup(asignEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignEmployeeButton)
                    .addComponent(assignEmployeesBackButton))
                .addContainerGap())
        );

        manageTrucksTabbedPane.addTab("Assign Employees", asignEmployeesPanel);

        maeSelectTruckLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maeSelectTruckLabel.setText("Select Truck:");

        manageAssignedEmployeesTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageAssignedEmployeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Employee State"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        manageAssignedEmployeesScrollPane.setViewportView(manageAssignedEmployeesTable);

        maeSelectTruckComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maeSelectTruckComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        showAssignedEmployeesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showAssignedEmployeesButton.setText("Show Assigned Employees");

        unassignEmployeeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        unassignEmployeeButton.setText("Unassign Employee");

        manageAssignedEmployeesBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        manageAssignedEmployeesBackButton.setText("Back");

        javax.swing.GroupLayout manageAsignedEmployeesPanelLayout = new javax.swing.GroupLayout(manageAsignedEmployeesPanel);
        manageAsignedEmployeesPanel.setLayout(manageAsignedEmployeesPanelLayout);
        manageAsignedEmployeesPanelLayout.setHorizontalGroup(
            manageAsignedEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAsignedEmployeesPanelLayout.createSequentialGroup()
                .addGroup(manageAsignedEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageAsignedEmployeesPanelLayout.createSequentialGroup()
                        .addGroup(manageAsignedEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maeSelectTruckLabel)
                            .addGroup(manageAsignedEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(showAssignedEmployeesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maeSelectTruckComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manageAssignedEmployeesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageAsignedEmployeesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(manageAssignedEmployeesBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                        .addComponent(unassignEmployeeButton)))
                .addContainerGap())
        );
        manageAsignedEmployeesPanelLayout.setVerticalGroup(
            manageAsignedEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageAsignedEmployeesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageAsignedEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageAsignedEmployeesPanelLayout.createSequentialGroup()
                        .addComponent(maeSelectTruckLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maeSelectTruckComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showAssignedEmployeesButton)
                        .addGap(0, 168, Short.MAX_VALUE))
                    .addComponent(manageAssignedEmployeesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageAsignedEmployeesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unassignEmployeeButton)
                    .addComponent(manageAssignedEmployeesBackButton))
                .addContainerGap())
        );

        manageTrucksTabbedPane.addTab("Manage Assigned Employees", manageAsignedEmployeesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageTrucksTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageTrucksLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageTrucksLabel)
                .addGap(12, 12, 12)
                .addComponent(manageTrucksTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setSetDefaultCloseOperation(){
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void addAddTrucksBackButtonAL(ActionListener al){
        this.addTruckBackButton.addActionListener(al);
    }
    
    public void addEditTrucksBackButtonAL(ActionListener al){
        this.editTrucksBackButton.addActionListener(al);
    }
    
    public void addAssignEmployeesBackButtonAL(ActionListener al){
        this.assignEmployeesBackButton.addActionListener(al);
    }
    
    public void addManageAssignedEmployeesBackButtonAL(ActionListener al){
        this.manageAssignedEmployeesBackButton.addActionListener(al);
    }
    
    public void addClearTextButtonAL(ActionListener al){
        this.clearTextButton.addActionListener(al);
    }
    
    public void addAddTruckButtonAL(ActionListener al){
        this.addTruckButton.addActionListener(al);
    }
    
    public void addEditTruckButtonAL(ActionListener al){
        this.editTruckButton.addActionListener(al);
    }
    
    public void addDeleteTruckButtonAL(ActionListener al){
        this.deleteTruckButton.addActionListener(al);
    }
    
    public void addAssignEmployeeButtonAL(ActionListener al){
        this.assignEmployeeButton.addActionListener(al);
    }
    
    public void addShowAssignedEmployeesButtonAL(ActionListener al){
        this.showAssignedEmployeesButton.addActionListener(al);
    }
    
    public void addUnassignEmployeeButtonAL(ActionListener al){
        this.unassignEmployeeButton.addActionListener(al);
    }
    
    public String getTruckNameTextFieldText(){
        return this.truckNameTextField.getText();
    }
    
    public void setTruckNameTextFieldText(String text){
        this.truckNameTextField.setText(text);
    }
    
    public String getTruckDescriptionTextAreaText(){
        return this.truckDescriptionTextArea.getText();
    }
    
    public void setTruckDescriptionTextAreaText(String text){
        this.truckDescriptionTextArea.setText(text);
    }
    
    public JComboBox getSelectTruckComboBox(){
        return this.selectTruckComboBox;
    }
    
    public JComboBox getSelectEmployeeComboBox(){
        return this.selectEmployeeComboBox;
    }
    
    public JComboBox getMAESelectTruckComboBox(){
        return this.maeSelectTruckComboBox;
    }
    
    public JTable getEditTrucksTable() {
        return this.editTrucksTable;
    }
    
    public void addEditTrucksTableModelListener(TableModelListener l) {
        DefaultTableModel model = (DefaultTableModel) this.editTrucksTable.getModel();
        model.addTableModelListener(l);
    }
    
    public void addEditTrucksTableMouseListener(MouseListener l) {
        this.editTrucksTable.addMouseListener(l);
    }
    
    public String getEditTrucksTableIDAt(int row, int col) {
        String id = "";
        if (row >= 0 && col >= 0) {
            id = editTrucksTable.getModel().getValueAt(row, col).toString();
        }
        return id;
    }
    
    public void clearTrucks() {
        DefaultTableModel model = (DefaultTableModel) this.editTrucksTable.getModel();
        model.setRowCount(0);
        editTrucksTable.clearSelection();
        editTrucksTable.revalidate();
        editTrucksTable.repaint();
    }

    public void addTruck(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.editTrucksTable.getModel();
        model.addRow(row);
    }
    
    public JTable getManageAssignedEmployeesTableTable() {
        return this.manageAssignedEmployeesTable;
    }
    
    public void addManageAssignedEmployeesTableModelListener(TableModelListener l) {
        DefaultTableModel model = (DefaultTableModel) this.manageAssignedEmployeesTable.getModel();
        model.addTableModelListener(l);
    }
    
    public void addManageAssignedEmployeesTableMouseListener(MouseListener l) {
        this.manageAssignedEmployeesTable.addMouseListener(l);
    }
    
    public String getManageAssignedEmployeesTableIDAt(int row, int col) {
        String id = "";
        if (row >= 0 && col >= 0) {
            id = manageAssignedEmployeesTable.getModel().getValueAt(row, col).toString();
        }
        return id;
    }
    
    public void clearAssignedEmployees() {
        DefaultTableModel model = (DefaultTableModel) this.manageAssignedEmployeesTable.getModel();
        model.setRowCount(0);
        manageAssignedEmployeesTable.clearSelection();
        manageAssignedEmployeesTable.revalidate();
        manageAssignedEmployeesTable.repaint();
    }

    public void addAssignedEmployee(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.manageAssignedEmployeesTable.getModel();
        model.addRow(row);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addStoreJPanel;
    private javax.swing.JButton addTruckBackButton;
    private javax.swing.JButton addTruckButton;
    private javax.swing.JScrollPane addTruckScrollPane;
    private javax.swing.JPanel asignEmployeesPanel;
    private javax.swing.JButton assignEmployeeButton;
    private javax.swing.JButton assignEmployeesBackButton;
    private javax.swing.JButton clearTextButton;
    private javax.swing.JButton deleteTruckButton;
    private javax.swing.JPanel editStoresJPanel;
    private javax.swing.JScrollPane editStoresScrollPane;
    private javax.swing.JButton editTruckButton;
    private javax.swing.JButton editTrucksBackButton;
    private javax.swing.JTable editTrucksTable;
    private javax.swing.JComboBox<String> maeSelectTruckComboBox;
    private javax.swing.JLabel maeSelectTruckLabel;
    private javax.swing.JPanel manageAsignedEmployeesPanel;
    private javax.swing.JButton manageAssignedEmployeesBackButton;
    private javax.swing.JScrollPane manageAssignedEmployeesScrollPane;
    private javax.swing.JTable manageAssignedEmployeesTable;
    private javax.swing.JLabel manageTrucksLabel;
    private javax.swing.JTabbedPane manageTrucksTabbedPane;
    private javax.swing.JComboBox<String> selectEmployeeComboBox;
    private javax.swing.JLabel selectEmployeeLabel;
    private javax.swing.JComboBox<String> selectTruckComboBox;
    private javax.swing.JLabel selectTruckLabel;
    private javax.swing.JButton showAssignedEmployeesButton;
    private javax.swing.JLabel truckDescriptionLabel;
    private javax.swing.JTextArea truckDescriptionTextArea;
    private javax.swing.JLabel truckNameLabel;
    private javax.swing.JTextField truckNameTextField;
    private javax.swing.JButton unassignEmployeeButton;
    // End of variables declaration//GEN-END:variables
}
