/*
 * SBDNO - Small Business Delivery Note Organizer
 * 
 * Copyright (C) 2025 Adrián González Hermida
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package view.searchManageDeliveryNoteView.editDeliveryNoteView;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JFrame;

/**
 *
 * @author EVEN
 */
public class EditDeliveryNoteFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditDeliveryNoteFrame.class.getName());

    /**
     * Creates new form EditDeliveryNoteFrame
     */
    public EditDeliveryNoteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        clientPhoneNumberTextField = new javax.swing.JTextField();
        selectDeliveryDateLabel = new javax.swing.JLabel();
        clientPhoneNumberLabel = new javax.swing.JLabel();
        selectDateButton = new javax.swing.JButton();
        selectTruckComboBox = new javax.swing.JComboBox<>();
        selectBusinessLabel = new javax.swing.JLabel();
        selectTruckLabel = new javax.swing.JLabel();
        selectBusinessComboBox = new javax.swing.JComboBox<>();
        amountTextField = new javax.swing.JTextField();
        selectStoreLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        selectStoreComboBox = new javax.swing.JComboBox<>();
        selectPDFButton = new javax.swing.JButton();
        selectSellerLabel = new javax.swing.JLabel();
        selectDeliveryNotePDFLabel = new javax.swing.JLabel();
        selectSellerComboBox = new javax.swing.JComboBox<>();
        confirmChangesButton = new javax.swing.JButton();
        clientNameLabel = new javax.swing.JLabel();
        resetEntriesButton = new javax.swing.JButton();
        clientNameTextField = new javax.swing.JTextField();
        editDeliveryNoteLabel = new javax.swing.JLabel();
        selectedPDFPathLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backButton.setText("Back");

        clientPhoneNumberTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        selectDeliveryDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryDateLabel.setText("Select Delivery Date:");

        clientPhoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientPhoneNumberLabel.setText("Client Phone Number:");

        selectDateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDateButton.setText("Select Date");

        selectTruckComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectTruckComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectBusinessLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectBusinessLabel.setText("Select Business:");

        selectTruckLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectTruckLabel.setText("Select Truck:");

        selectBusinessComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectBusinessComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        amountTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        selectStoreLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectStoreLabel.setText("Select Store:");

        amountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amountLabel.setText("Amount:");

        selectStoreComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectStoreComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectPDFButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectPDFButton.setText("Select PDF");

        selectSellerLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectSellerLabel.setText("Select Seller:");

        selectDeliveryNotePDFLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryNotePDFLabel.setText("Select Delivery Note PDF:");

        selectSellerComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectSellerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        confirmChangesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmChangesButton.setText("Confirm Changes");

        clientNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientNameLabel.setText("Client Name:");

        resetEntriesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetEntriesButton.setText("Reset Entries");

        clientNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        editDeliveryNoteLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        editDeliveryNoteLabel.setText("Edit Delivery Note");

        selectedPDFPathLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectedPDFPathLabel.setText("Selected PDF path");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editDeliveryNoteLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(selectDeliveryDateLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(selectBusinessLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(selectDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(selectBusinessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectStoreLabel)
                                    .addComponent(selectStoreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectSellerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectSellerLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectTruckLabel)
                                    .addComponent(selectTruckComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientNameLabel)
                            .addComponent(clientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(clientPhoneNumberLabel)
                                .addGap(23, 23, 23)
                                .addComponent(amountLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectDeliveryNotePDFLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(clientPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectPDFButton)
                                .addGap(43, 43, 43))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(422, 422, 422)
                        .addComponent(resetEntriesButton)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(confirmChangesButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(selectedPDFPathLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editDeliveryNoteLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDeliveryDateLabel)
                    .addComponent(selectBusinessLabel)
                    .addComponent(selectStoreLabel)
                    .addComponent(selectSellerLabel)
                    .addComponent(selectTruckLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDateButton)
                    .addComponent(selectBusinessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectStoreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectSellerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectTruckComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameLabel)
                    .addComponent(clientPhoneNumberLabel)
                    .addComponent(amountLabel)
                    .addComponent(selectDeliveryNotePDFLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectPDFButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedPDFPathLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmChangesButton)
                    .addComponent(resetEntriesButton)
                    .addComponent(backButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDefaultCloseOperation() {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void addResetEntriesButtonAL(ActionListener al) {
        this.resetEntriesButton.addActionListener(al);
    }

    public void addConfirmChangesButtonAL(ActionListener al) {
        this.confirmChangesButton.addActionListener(al);
    }

    public void addBackButtonAL(ActionListener al) {
        this.backButton.addActionListener(al);
    }

    public void addSelectPDFButtonAL(ActionListener al) {
        this.selectPDFButton.addActionListener(al);
    }

    public void addSelectDateButtonAL(ActionListener al) {
        this.selectDateButton.addActionListener(al);
    }

    public void addSelectBusinesComboBoxAL(ActionListener al) {
        this.selectBusinessComboBox.addActionListener(al);
    }

    public void addSelectStoreComboBoxAL(ActionListener al) {
        this.selectStoreComboBox.addActionListener(al);
    }

    public void addSelectSellerComboBoxAL(ActionListener al) {
        this.selectSellerComboBox.addActionListener(al);
    }

    public void addSelectTruckComboBoxAL(ActionListener al) {
        this.selectTruckComboBox.addActionListener(al);
    }

    public JComboBox getSelectBusinessComboBox() {
        return this.selectBusinessComboBox;
    }

    public JComboBox getSelectStoreComboBox() {
        return this.selectStoreComboBox;
    }

    public JComboBox getSelectSellerComboBox() {
        return this.selectSellerComboBox;
    }

    public JComboBox getSelectTruckComboBox() {
        return this.selectTruckComboBox;
    }

    public String getAmountTextFieldText() {
        return this.amountTextField.getText();
    }

    public String getClientNameTextFieldText() {
        return this.clientNameTextField.getText();
    }

    public String getClientPhoneNumberTextFieldText() {
        return this.clientPhoneNumberTextField.getText();
    }

    public void setAmountTextFieldText(String text) {
        this.amountTextField.setText(text);
    }

    public void setClientNameTextFieldText(String text) {
        this.clientNameTextField.setText(text);
    }

    public void setClientPhoneNumberTextFieldText(String text) {
        this.clientPhoneNumberTextField.setText(text);
    }

    public void setSelectDateButtonText(String text) {
        this.selectDateButton.setText(text);
    }

    public void setSelectedPDFPathLabelText(String text) {
        this.selectedPDFPathLabel.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel clientNameLabel;
    private javax.swing.JTextField clientNameTextField;
    private javax.swing.JLabel clientPhoneNumberLabel;
    private javax.swing.JTextField clientPhoneNumberTextField;
    private javax.swing.JButton confirmChangesButton;
    private javax.swing.JLabel editDeliveryNoteLabel;
    private javax.swing.JButton resetEntriesButton;
    private javax.swing.JComboBox<String> selectBusinessComboBox;
    private javax.swing.JLabel selectBusinessLabel;
    private javax.swing.JButton selectDateButton;
    private javax.swing.JLabel selectDeliveryDateLabel;
    private javax.swing.JLabel selectDeliveryNotePDFLabel;
    private javax.swing.JButton selectPDFButton;
    private javax.swing.JComboBox<String> selectSellerComboBox;
    private javax.swing.JLabel selectSellerLabel;
    private javax.swing.JComboBox<String> selectStoreComboBox;
    private javax.swing.JLabel selectStoreLabel;
    private javax.swing.JComboBox<String> selectTruckComboBox;
    private javax.swing.JLabel selectTruckLabel;
    private javax.swing.JLabel selectedPDFPathLabel;
    // End of variables declaration//GEN-END:variables
}
