/*
 * SBDNO - Small Business Delivery Note Organizer
 * 
 * Copyright (C) 2025 Adrián González Hermida
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package view.searchManageDeliveryNoteView;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EVEN
 */
public class SearchManageDeliveryNoteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SearchManageDeliveryNoteFrame.class.getName());

    /**
     * Creates new form SearchManageDeliveryNoteFrame
     */
    public SearchManageDeliveryNoteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchManageDeliveryNoteLabel = new javax.swing.JLabel();
        searchManageDeliveryNoteScrollPane = new javax.swing.JScrollPane();
        searchManageDeliveryNoteTable = new javax.swing.JTable();
        filterDeliveryNotesButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        deleteDeliveryNoteButton = new javax.swing.JButton();
        editDeliveryNoteButton = new javax.swing.JButton();
        viewPDFButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchManageDeliveryNoteLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        searchManageDeliveryNoteLabel.setText("Search / Manage Delivery Notes");

        searchManageDeliveryNoteTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchManageDeliveryNoteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Delivery Note ID", "Introduction Date", "Delivery Date", "Client id | Name", "Client Phone Number", "Business id | Name", "Store id | Name", "Seller id | Name", "Truck id | Name", "Amount", "PDF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        searchManageDeliveryNoteScrollPane.setViewportView(searchManageDeliveryNoteTable);

        filterDeliveryNotesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filterDeliveryNotesButton.setText("Filter Delivery Notes");

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backButton.setText("Back");

        deleteDeliveryNoteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteDeliveryNoteButton.setText("Delete Delivery Note");

        editDeliveryNoteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editDeliveryNoteButton.setText("Edit Delivery Note");

        viewPDFButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewPDFButton.setText("View PDF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchManageDeliveryNoteScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchManageDeliveryNoteLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 692, Short.MAX_VALUE)
                        .addComponent(viewPDFButton)
                        .addGap(18, 18, 18)
                        .addComponent(editDeliveryNoteButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteDeliveryNoteButton)
                        .addGap(18, 18, 18)
                        .addComponent(filterDeliveryNotesButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchManageDeliveryNoteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchManageDeliveryNoteScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterDeliveryNotesButton)
                    .addComponent(backButton)
                    .addComponent(deleteDeliveryNoteButton)
                    .addComponent(editDeliveryNoteButton)
                    .addComponent(viewPDFButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDefaultCloseOperation(){
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public JTable getSearchManageDeliveryNoteTable(){
        return this.searchManageDeliveryNoteTable;
    }
    
    public void addBackButtonAL(ActionListener al){
        this.backButton.addActionListener(al);
    }
    
    public void addViewPDFButtonAL(ActionListener al){
        this.viewPDFButton.addActionListener(al);
    }
    
    public void addEditDeliveryNoteButtonAL(ActionListener al){
        this.editDeliveryNoteButton.addActionListener(al);
    }
    
    public void addDeleteDeliveryNoteButtonAL(ActionListener al){
        this.deleteDeliveryNoteButton.addActionListener(al);
    }
    
    public void addFilterDeliveryNotesButtonAL(ActionListener al){
        this.filterDeliveryNotesButton.addActionListener(al);
    }
    
    public void addSearchManageDeliveryNotesTableModelListener(TableModelListener l) {
        DefaultTableModel model = (DefaultTableModel) this.searchManageDeliveryNoteTable.getModel();
        model.addTableModelListener(l);
    }
    
    public void addSearchManageDeliveryNoteTableMouseListener(MouseListener l) {
        this.searchManageDeliveryNoteTable.addMouseListener(l);
    }
    
    public String getSearchManageDeliveryNoteTableIDAt(int row, int col) {
        String id = "";
        if (row >= 0 && col >= 0) {
            id = searchManageDeliveryNoteTable.getModel().getValueAt(row, col).toString();
        }
        return id;
    }

    public void clearDeliveryNotes() {
        DefaultTableModel model = (DefaultTableModel) this.searchManageDeliveryNoteTable.getModel();
        model.setRowCount(0);
        searchManageDeliveryNoteTable.clearSelection();
        searchManageDeliveryNoteTable.revalidate();
        searchManageDeliveryNoteTable.repaint();
    }

    public void addDeliveryNote(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.searchManageDeliveryNoteTable.getModel();
        model.addRow(row);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteDeliveryNoteButton;
    private javax.swing.JButton editDeliveryNoteButton;
    private javax.swing.JButton filterDeliveryNotesButton;
    private javax.swing.JLabel searchManageDeliveryNoteLabel;
    private javax.swing.JScrollPane searchManageDeliveryNoteScrollPane;
    private javax.swing.JTable searchManageDeliveryNoteTable;
    private javax.swing.JButton viewPDFButton;
    // End of variables declaration//GEN-END:variables
}
