/*
 * SBDNO - Small Business Delivery Note Organizer
 * 
 * Copyright (C) 2025 Adrián González Hermida
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package view.addDeliveryNoteView;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JFrame;

/**
 *
 * @author EVEN
 */
public class AddDeliveryNoteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddDeliveryNoteFrame.class.getName());

    /**
     * Creates new form AddDeliveryNoteFrame
     */
    public AddDeliveryNoteFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDeliveryNoteLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        selectDeliveryDateLabel = new javax.swing.JLabel();
        selectDateButton = new javax.swing.JButton();
        selectBusinessLabel = new javax.swing.JLabel();
        selectBusinessComboBox = new javax.swing.JComboBox<>();
        selectStoreLabel = new javax.swing.JLabel();
        selectStoreComboBox = new javax.swing.JComboBox<>();
        selectSellerLabel = new javax.swing.JLabel();
        selectSellerComboBox = new javax.swing.JComboBox<>();
        clientNameLabel = new javax.swing.JLabel();
        clientNameTextField = new javax.swing.JTextField();
        clientPhoneNumberTextField = new javax.swing.JTextField();
        clientPhoneNumberLabel = new javax.swing.JLabel();
        selectTruckComboBox = new javax.swing.JComboBox<>();
        selectTruckLabel = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        selectPDFButton = new javax.swing.JButton();
        selectDeliveryNotePDFLabel = new javax.swing.JLabel();
        addDeliveryNoteButton = new javax.swing.JButton();
        clearEntriesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addDeliveryNoteLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addDeliveryNoteLabel.setText("Add Delivery Note");

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backButton.setText("Back");

        selectDeliveryDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryDateLabel.setText("Select Delivery Date:");

        selectDateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDateButton.setText("Select Date");

        selectBusinessLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectBusinessLabel.setText("Select Business:");

        selectBusinessComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectBusinessComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectStoreLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectStoreLabel.setText("Select Store:");

        selectStoreComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectStoreComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectSellerLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectSellerLabel.setText("Select Seller:");

        selectSellerComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectSellerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        clientNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientNameLabel.setText("Client Name:");

        clientNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        clientPhoneNumberTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        clientPhoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientPhoneNumberLabel.setText("Client Phone Number:");

        selectTruckComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectTruckComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectTruckLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectTruckLabel.setText("Select Truck:");

        amountTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        amountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amountLabel.setText("Amount:");

        selectPDFButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectPDFButton.setText("Select PDF");

        selectDeliveryNotePDFLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryNotePDFLabel.setText("Select Delivery Note PDF:");

        addDeliveryNoteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addDeliveryNoteButton.setText("Add Delivery Note");

        clearEntriesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearEntriesButton.setText("Clear Entries");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearEntriesButton)
                        .addGap(51, 51, 51)
                        .addComponent(addDeliveryNoteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientNameLabel)
                            .addComponent(clientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clientPhoneNumberLabel)
                                .addGap(23, 23, 23)
                                .addComponent(amountLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectDeliveryNotePDFLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clientPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectPDFButton)
                                .addGap(35, 35, 35))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addDeliveryNoteLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(selectDeliveryDateLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(selectBusinessLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(selectDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(selectBusinessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectStoreLabel)
                                    .addComponent(selectStoreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectSellerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectSellerLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectTruckLabel)
                                    .addComponent(selectTruckComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addDeliveryNoteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDeliveryDateLabel)
                    .addComponent(selectBusinessLabel)
                    .addComponent(selectStoreLabel)
                    .addComponent(selectSellerLabel)
                    .addComponent(selectTruckLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDateButton)
                    .addComponent(selectBusinessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectStoreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectSellerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectTruckComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameLabel)
                    .addComponent(clientPhoneNumberLabel)
                    .addComponent(amountLabel)
                    .addComponent(selectDeliveryNotePDFLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectPDFButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(addDeliveryNoteButton)
                    .addComponent(clearEntriesButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDefaultCloseOperation(){
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void addClearEntriesButtonAL(ActionListener al){
        this.clearEntriesButton.addActionListener(al);
    }
    
    public void addAddDeliveryNoteButtonAL(ActionListener al){
        this.addDeliveryNoteButton.addActionListener(al);
    }
    
    public void addBackButtonAL(ActionListener al){
        this.backButton.addActionListener(al);
    }
    
    public void addSelectPDFButtonAL(ActionListener al){
        this.selectPDFButton.addActionListener(al);
    }
    
    public void addSelectDateButtonAL(ActionListener al){
        this.selectDateButton.addActionListener(al);
    }
    
    public void addSelectBusinesComboBoxAL(ActionListener al){
        this.selectBusinessComboBox.addActionListener(al);
    }
    
    public void addSelectStoreComboBoxAL(ActionListener al){
        this.selectStoreComboBox.addActionListener(al);
    }
    
    public void addSelectSellerComboBoxAL(ActionListener al){
        this.selectSellerComboBox.addActionListener(al);
    }
    
    public void addSelectTruckComboBoxAL(ActionListener al){
        this.selectTruckComboBox.addActionListener(al);
    }
    
    public JComboBox getSelectBusinessComboBox(){
        return this.selectBusinessComboBox;
    }
    
    public JComboBox getSelectStoreComboBox(){
        return this.selectStoreComboBox;
    }
    
    public JComboBox getSelectSellerComboBox(){
        return this.selectSellerComboBox;
    }
    
    public JComboBox getSelectTruckComboBox(){
        return this.selectTruckComboBox;
    }
    
    public String getAmountTextFieldText(){
        return this.amountTextField.getText();
    }
    
    public String getClientNameTextFieldText(){
        return this.clientNameTextField.getText();
    }
    
    public String getClientPhoneNumberTextFieldText(){
        return this.clientPhoneNumberTextField.getText();
    }
    
    public void setAmountTextFieldText(String text){
        this.amountTextField.setText(text);
    }
    
    public void setClientNameTextFieldText(String text){
        this.clientNameTextField.setText(text);
    }
    
    public void setClientPhoneNumberTextFieldText(String text){
        this.clientPhoneNumberTextField.setText(text);
    }
    
    public void setSelectDateButtonText(String text){
        this.selectDateButton.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDeliveryNoteButton;
    private javax.swing.JLabel addDeliveryNoteLabel;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearEntriesButton;
    private javax.swing.JLabel clientNameLabel;
    private javax.swing.JTextField clientNameTextField;
    private javax.swing.JLabel clientPhoneNumberLabel;
    private javax.swing.JTextField clientPhoneNumberTextField;
    private javax.swing.JComboBox<String> selectBusinessComboBox;
    private javax.swing.JLabel selectBusinessLabel;
    private javax.swing.JButton selectDateButton;
    private javax.swing.JLabel selectDeliveryDateLabel;
    private javax.swing.JLabel selectDeliveryNotePDFLabel;
    private javax.swing.JButton selectPDFButton;
    private javax.swing.JComboBox<String> selectSellerComboBox;
    private javax.swing.JLabel selectSellerLabel;
    private javax.swing.JComboBox<String> selectStoreComboBox;
    private javax.swing.JLabel selectStoreLabel;
    private javax.swing.JComboBox<String> selectTruckComboBox;
    private javax.swing.JLabel selectTruckLabel;
    // End of variables declaration//GEN-END:variables
}
