/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.manageSellersView;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EVEN
 */
public class ManageSellersFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageSellersFrame.class.getName());

    /**
     * Creates new form ManageSellersFrame
     */
    public ManageSellersFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageSellersTabbedPane = new javax.swing.JTabbedPane();
        addStoreJPanel = new javax.swing.JPanel();
        selectStoreLabel = new javax.swing.JLabel();
        storeNameLabel = new javax.swing.JLabel();
        sellerNameTextField = new javax.swing.JTextField();
        clearTextButton = new javax.swing.JButton();
        addSellerButton = new javax.swing.JButton();
        addSellerBackButton = new javax.swing.JButton();
        selectStoreComboBox = new javax.swing.JComboBox<>();
        editStoresJPanel = new javax.swing.JPanel();
        editStoresScrollPane = new javax.swing.JScrollPane();
        editSellersTable = new javax.swing.JTable();
        editSellerButton = new javax.swing.JButton();
        deleteSellerButton = new javax.swing.JButton();
        editSellersBackButton = new javax.swing.JButton();
        manageSellersLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageSellersTabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        selectStoreLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectStoreLabel.setText("Select Store:");

        storeNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        storeNameLabel.setText("Seller Name:");

        sellerNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        clearTextButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearTextButton.setText("Clear Text");

        addSellerButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addSellerButton.setText("Add Seller");

        addSellerBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addSellerBackButton.setText("Back");

        selectStoreComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectStoreComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout addStoreJPanelLayout = new javax.swing.GroupLayout(addStoreJPanel);
        addStoreJPanel.setLayout(addStoreJPanelLayout);
        addStoreJPanelLayout.setHorizontalGroup(
            addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStoreJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSellerBackButton)
                    .addGroup(addStoreJPanelLayout.createSequentialGroup()
                        .addComponent(selectStoreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectStoreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStoreJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clearTextButton)
                        .addGap(18, 18, 18)
                        .addComponent(addSellerButton))
                    .addGroup(addStoreJPanelLayout.createSequentialGroup()
                        .addComponent(storeNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellerNameTextField)))
                .addContainerGap())
        );
        addStoreJPanelLayout.setVerticalGroup(
            addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStoreJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectStoreLabel)
                    .addComponent(storeNameLabel)
                    .addComponent(sellerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectStoreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearTextButton)
                    .addComponent(addSellerButton)
                    .addComponent(addSellerBackButton))
                .addContainerGap())
        );

        manageSellersTabbedPane.addTab("Add Seller", addStoreJPanel);

        editSellersTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editSellersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Store ID", "Seller ID", "Store Name", "Seller Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        editStoresScrollPane.setViewportView(editSellersTable);

        editSellerButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editSellerButton.setText("Edit Seller");

        deleteSellerButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteSellerButton.setText("Delete Seller");

        editSellersBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editSellersBackButton.setText("Back");

        javax.swing.GroupLayout editStoresJPanelLayout = new javax.swing.GroupLayout(editStoresJPanel);
        editStoresJPanel.setLayout(editStoresJPanelLayout);
        editStoresJPanelLayout.setHorizontalGroup(
            editStoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStoresJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editStoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editStoresScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editStoresJPanelLayout.createSequentialGroup()
                        .addComponent(editSellersBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteSellerButton)
                        .addGap(18, 18, 18)
                        .addComponent(editSellerButton)))
                .addContainerGap())
        );
        editStoresJPanelLayout.setVerticalGroup(
            editStoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStoresJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editStoresScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editStoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editSellerButton)
                    .addComponent(deleteSellerButton)
                    .addComponent(editSellersBackButton))
                .addContainerGap())
        );

        manageSellersTabbedPane.addTab("Edit Sellers", editStoresJPanel);

        manageSellersLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageSellersLabel.setText("Manage Sellers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageSellersTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageSellersLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageSellersLabel)
                .addGap(12, 12, 12)
                .addComponent(manageSellersTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setSetDefaultCloseOperation(){
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void addAddSellerBackButtonAL(ActionListener al){
        this.addSellerBackButton.addActionListener(al);
    }
    
    public void addEditSellersBackButtonAL(ActionListener al){
        this.editSellersBackButton.addActionListener(al);
    }
    
    public void addClearTextButtonAL(ActionListener al){
        this.clearTextButton.addActionListener(al);
    }
    
    public void addAddSellerButtonAL(ActionListener al){
        this.addSellerButton.addActionListener(al);
    }
    
    public void addEditSellerButtonAL(ActionListener al){
        this.editSellerButton.addActionListener(al);
    }
    
    public void addDeleteSellerButtonAL(ActionListener al){
        this.deleteSellerButton.addActionListener(al);
    }
    
    public String getSellerNameTextFieldText(){
        return this.sellerNameTextField.getText();
    }
    
    public void setSellerNameTextFieldText(String text){
        this.sellerNameTextField.setText(text);
    }
    
    public JTable getEditSellersTable() {
        return this.editSellersTable;
    }
    
    public JComboBox getSelectStoreComboBox(){
        return this.selectStoreComboBox;
    }
    
    public void addEditSellersTableModelListener(TableModelListener l) {
        DefaultTableModel model = (DefaultTableModel) this.editSellersTable.getModel();
        model.addTableModelListener(l);
    }
    
    public void addEditSellersTableMouseListener(MouseListener l) {
        this.editSellersTable.addMouseListener(l);
    }
    
    public String getEditSellersTableIDAt(int row, int col) {
        String id = "";
        if (row >= 0 && col >= 0) {
            id = editSellersTable.getModel().getValueAt(row, col).toString();
        }
        return id;
    }
    
    public void clearSellers() {
        DefaultTableModel model = (DefaultTableModel) this.editSellersTable.getModel();
        model.setRowCount(0);
        editSellersTable.clearSelection();
        editSellersTable.revalidate();
        editSellersTable.repaint();
    }

    public void addSeller(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.editSellersTable.getModel();
        model.addRow(row);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSellerBackButton;
    private javax.swing.JButton addSellerButton;
    private javax.swing.JPanel addStoreJPanel;
    private javax.swing.JButton clearTextButton;
    private javax.swing.JButton deleteSellerButton;
    private javax.swing.JButton editSellerButton;
    private javax.swing.JButton editSellersBackButton;
    private javax.swing.JTable editSellersTable;
    private javax.swing.JPanel editStoresJPanel;
    private javax.swing.JScrollPane editStoresScrollPane;
    private javax.swing.JLabel manageSellersLabel;
    private javax.swing.JTabbedPane manageSellersTabbedPane;
    private javax.swing.JComboBox<String> selectStoreComboBox;
    private javax.swing.JLabel selectStoreLabel;
    private javax.swing.JTextField sellerNameTextField;
    private javax.swing.JLabel storeNameLabel;
    // End of variables declaration//GEN-END:variables
}
