/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.manageBusinessesView;

import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EVEN
 */
public class ManageBusinessesDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddBusinessDialog
     */
    public ManageBusinessesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageBusinessLabel = new javax.swing.JLabel();
        manageBusinessTabbedPane = new javax.swing.JTabbedPane();
        addBusinessJPanel = new javax.swing.JPanel();
        businessNameLabel = new javax.swing.JLabel();
        businessNameTextField = new javax.swing.JTextField();
        percentageCommissionLabel = new javax.swing.JLabel();
        percentageCommissionTextField = new javax.swing.JTextField();
        clearTextButton = new javax.swing.JButton();
        addBusinessButton = new javax.swing.JButton();
        editBusinessesJPanel = new javax.swing.JPanel();
        editBusinessesScrollPane = new javax.swing.JScrollPane();
        editBusinessesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        manageBusinessLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageBusinessLabel.setText("Manage Businesses");

        businessNameLabel.setText("Business Name:");

        percentageCommissionLabel.setText("Percentage Commission:");

        clearTextButton.setText("Clear Text");

        addBusinessButton.setText("Add Business");

        javax.swing.GroupLayout addBusinessJPanelLayout = new javax.swing.GroupLayout(addBusinessJPanel);
        addBusinessJPanel.setLayout(addBusinessJPanelLayout);
        addBusinessJPanelLayout.setHorizontalGroup(
            addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(businessNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(businessNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                        .addComponent(clearTextButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBusinessButton))
                    .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                        .addComponent(percentageCommissionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(percentageCommissionTextField)))
                .addContainerGap())
        );
        addBusinessJPanelLayout.setVerticalGroup(
            addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(businessNameLabel)
                    .addComponent(businessNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percentageCommissionLabel)
                    .addComponent(percentageCommissionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearTextButton)
                    .addComponent(addBusinessButton))
                .addContainerGap())
        );

        manageBusinessTabbedPane.addTab("Add Business", addBusinessJPanel);

        editBusinessesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Business Name", "Percentage Commission"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        editBusinessesScrollPane.setViewportView(editBusinessesTable);

        javax.swing.GroupLayout editBusinessesJPanelLayout = new javax.swing.GroupLayout(editBusinessesJPanel);
        editBusinessesJPanel.setLayout(editBusinessesJPanelLayout);
        editBusinessesJPanelLayout.setHorizontalGroup(
            editBusinessesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editBusinessesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editBusinessesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        editBusinessesJPanelLayout.setVerticalGroup(
            editBusinessesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editBusinessesJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editBusinessesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        manageBusinessTabbedPane.addTab("Edit Businesses", editBusinessesJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageBusinessTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageBusinessLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageBusinessLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageBusinessTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getBusinessNameTextField() {
        String text = businessNameTextField.getText();
        return text;
    }

    public int getPercentageCommissionTextField() {
        int num = Integer.parseInt(percentageCommissionTextField.getText());
        return num;
    }

    public void addAddBusinessButtonAL(ActionListener al) {
        addBusinessButton.addActionListener(al);
    }

    public void addClearTextButtonAL(ActionListener al) {
        clearTextButton.addActionListener(al);
    }

    public void setBusinessNameTextField(String text) {
        businessNameTextField.setText(text);
    }
    
    public void setPercentageCommissionTextField(String text) {
        percentageCommissionTextField.setText(text);
    }

    public void clearBusinesses() {
        DefaultTableModel model = (DefaultTableModel) this.editBusinessesTable.getModel();
        model.setRowCount(0);
        editBusinessesTable.clearSelection();
        editBusinessesTable.revalidate();
        editBusinessesTable.repaint();
    }

    public void addBusiness(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.editBusinessesTable.getModel();
        model.addRow(row);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBusinessButton;
    private javax.swing.JPanel addBusinessJPanel;
    private javax.swing.JLabel businessNameLabel;
    private javax.swing.JTextField businessNameTextField;
    private javax.swing.JButton clearTextButton;
    private javax.swing.JPanel editBusinessesJPanel;
    private javax.swing.JScrollPane editBusinessesScrollPane;
    private javax.swing.JTable editBusinessesTable;
    private javax.swing.JLabel manageBusinessLabel;
    private javax.swing.JTabbedPane manageBusinessTabbedPane;
    private javax.swing.JLabel percentageCommissionLabel;
    private javax.swing.JTextField percentageCommissionTextField;
    // End of variables declaration//GEN-END:variables
}
