/*
 * SBDNO - Small Business Delivery Note Organizer
 * 
 * Copyright (C) 2025 Adrián González Hermida
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package view.manageTrucksView.editTruckView;

import java.awt.event.ActionListener;

/**
 *
 * @author EVEN
 */
public class EditTruckDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditTruckDialog.class.getName());

    /**
     * Creates new form EditTruckDialog
     */
    public EditTruckDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        truckNameLabel = new javax.swing.JLabel();
        truckNameTextField = new javax.swing.JTextField();
        truckDescriptionLabel = new javax.swing.JLabel();
        truckDescriptionScrollPane = new javax.swing.JScrollPane();
        truckDescriptionTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        acceptButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acceptButton.setText("Accept");

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");

        truckNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        truckNameLabel.setText("Truck Name / License Plate:");

        truckNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        truckDescriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        truckDescriptionLabel.setText("Truck Description:");

        truckDescriptionTextArea.setColumns(20);
        truckDescriptionTextArea.setRows(5);
        truckDescriptionScrollPane.setViewportView(truckDescriptionTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(truckNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(truckNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acceptButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(truckDescriptionLabel)
                        .addGap(18, 18, 18)
                        .addComponent(truckDescriptionScrollPane)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(truckNameLabel)
                    .addComponent(truckNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(truckDescriptionLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(truckDescriptionScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addAcceptButtonAL(ActionListener al){
        this.acceptButton.addActionListener(al);
    }
    
    public void addCancelButtonAL(ActionListener al){
        this.cancelButton.addActionListener(al);
    }
    
    public String getTruckNameTextFieldText(){
        return this.truckNameTextField.getText();
    }
    
    public void setTruckNameTextFieldText(String text){
        this.truckNameTextField.setText(text);
    }
    
    public String getTruckDescriptionTextAreaText(){
        return this.truckDescriptionTextArea.getText();
    }
    
    public void setTruckDescriptionTextAreaText(String text){
        this.truckDescriptionTextArea.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel truckDescriptionLabel;
    private javax.swing.JScrollPane truckDescriptionScrollPane;
    private javax.swing.JTextArea truckDescriptionTextArea;
    private javax.swing.JLabel truckNameLabel;
    private javax.swing.JTextField truckNameTextField;
    // End of variables declaration//GEN-END:variables
}
