/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.manageBusinessesView.editBusinessView;

import java.awt.event.ActionListener;

/**
 *
 * @author EVEN
 */
public class EditBusinessDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditBusinessDialog.class.getName());

    /**
     * Creates new form EditBusinessDialog
     */
    public EditBusinessDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        businessNameLabel = new javax.swing.JLabel();
        businessNameTextField = new javax.swing.JTextField();
        percentageCommissionLabel = new javax.swing.JLabel();
        percentageCommissionTextField = new javax.swing.JTextField();
        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        businessNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        businessNameLabel.setText("Business Name:");

        businessNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        percentageCommissionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        percentageCommissionLabel.setText("Percentage Commission:");

        percentageCommissionTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        acceptButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acceptButton.setText("Accept");

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(businessNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(businessNameTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acceptButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(percentageCommissionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(percentageCommissionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(businessNameLabel)
                    .addComponent(businessNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentageCommissionLabel)
                    .addComponent(percentageCommissionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getBusinessNameTextFieldText(){
        return this.businessNameTextField.getText();
    }
    
    public String getPercentageCommissionTextFieldText(){
        return this.percentageCommissionTextField.getText();
    }
    
    public void setBusinessNameTextFieldText(String text){
        this.businessNameTextField.setText(text);
    }
    
    public void setPercentageCommissionTextFieldText(String text){
        this.percentageCommissionTextField.setText(text);
    }
    
    public void addAcceptButtonActionListener(ActionListener al){
        this.acceptButton.addActionListener(al);
    }
    
    public void addCancelButtonActionListener(ActionListener al){
        this.cancelButton.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JLabel businessNameLabel;
    private javax.swing.JTextField businessNameTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel percentageCommissionLabel;
    private javax.swing.JTextField percentageCommissionTextField;
    // End of variables declaration//GEN-END:variables
}
