package view.manageBusinessesView;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EVEN
 */
public class ManageBusinessesDialog extends javax.swing.JFrame {

    /**
     * Creates new form AddBusinessDialog
     */
    public ManageBusinessesDialog(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageBusinessLabel = new javax.swing.JLabel();
        manageBusinessTabbedPane = new javax.swing.JTabbedPane();
        addBusinessJPanel = new javax.swing.JPanel();
        businessNameLabel = new javax.swing.JLabel();
        businessNameTextField = new javax.swing.JTextField();
        percentageCommissionLabel = new javax.swing.JLabel();
        percentageCommissionTextField = new javax.swing.JTextField();
        clearTextButton = new javax.swing.JButton();
        addBusinessButton = new javax.swing.JButton();
        addBusinessBackButton = new javax.swing.JButton();
        editBusinessesJPanel = new javax.swing.JPanel();
        editBusinessesScrollPane = new javax.swing.JScrollPane();
        editBusinessesTable = new javax.swing.JTable();
        editBusinessButton = new javax.swing.JButton();
        deleteBusinessButton = new javax.swing.JButton();
        editBusinessesBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        manageBusinessLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageBusinessLabel.setText("Manage Businesses");

        manageBusinessTabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        businessNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        businessNameLabel.setText("Business Name:");

        businessNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        percentageCommissionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        percentageCommissionLabel.setText("Percentage Commission:");

        percentageCommissionTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        clearTextButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearTextButton.setText("Clear Text");

        addBusinessButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addBusinessButton.setText("Add Business");

        addBusinessBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addBusinessBackButton.setText("Back");

        javax.swing.GroupLayout addBusinessJPanelLayout = new javax.swing.GroupLayout(addBusinessJPanel);
        addBusinessJPanel.setLayout(addBusinessJPanelLayout);
        addBusinessJPanelLayout.setHorizontalGroup(
            addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                        .addComponent(businessNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(businessNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addBusinessBackButton))
                .addGap(18, 18, 18)
                .addGroup(addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clearTextButton)
                        .addGap(18, 18, 18)
                        .addComponent(addBusinessButton))
                    .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                        .addComponent(percentageCommissionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(percentageCommissionTextField)))
                .addContainerGap())
        );
        addBusinessJPanelLayout.setVerticalGroup(
            addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(businessNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(businessNameLabel)
                    .addComponent(percentageCommissionLabel)
                    .addComponent(percentageCommissionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearTextButton)
                    .addComponent(addBusinessButton)
                    .addComponent(addBusinessBackButton))
                .addContainerGap())
        );

        manageBusinessTabbedPane.addTab("Add Business", addBusinessJPanel);

        editBusinessesTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editBusinessesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Business ID", "Business Name", "Percentage Commission"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        editBusinessesScrollPane.setViewportView(editBusinessesTable);

        editBusinessButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editBusinessButton.setText("Edit Business");

        deleteBusinessButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteBusinessButton.setText("Delete Business");

        editBusinessesBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editBusinessesBackButton.setText("Back");

        javax.swing.GroupLayout editBusinessesJPanelLayout = new javax.swing.GroupLayout(editBusinessesJPanel);
        editBusinessesJPanel.setLayout(editBusinessesJPanelLayout);
        editBusinessesJPanelLayout.setHorizontalGroup(
            editBusinessesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editBusinessesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editBusinessesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editBusinessesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editBusinessesJPanelLayout.createSequentialGroup()
                        .addComponent(editBusinessesBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteBusinessButton)
                        .addGap(18, 18, 18)
                        .addComponent(editBusinessButton)))
                .addContainerGap())
        );
        editBusinessesJPanelLayout.setVerticalGroup(
            editBusinessesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editBusinessesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editBusinessesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(editBusinessesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBusinessButton)
                    .addComponent(deleteBusinessButton)
                    .addComponent(editBusinessesBackButton))
                .addContainerGap())
        );

        manageBusinessTabbedPane.addTab("Edit Businesses", editBusinessesJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageBusinessTabbedPane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageBusinessLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageBusinessLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageBusinessTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getEditBusinessesTable() {
        return editBusinessesTable;
    }
    
    public String getBusinessNameTextField() {
        String text = businessNameTextField.getText();
        return text;
    }

    public String getPercentageCommissionTextField() {
        String num = percentageCommissionTextField.getText();
        return num;
    }

    public void addAddBusinessButtonAL(ActionListener al) {
        addBusinessButton.addActionListener(al);
    }

    public void addClearTextButtonAL(ActionListener al) {
        clearTextButton.addActionListener(al);
    }
    
    public void addAddBusinessBackButtonAL(ActionListener al) {
        addBusinessBackButton.addActionListener(al);
    }
    
    public void addEditBusinessesBackButtonAL(ActionListener al) {
        editBusinessesBackButton.addActionListener(al);
    }
    
    public void addDeleteBusinessButtonAL(ActionListener al) {
        deleteBusinessButton.addActionListener(al);
    }

    public void addEditBusinessButtonAL(ActionListener al) {
        editBusinessButton.addActionListener(al);
    }

    public void setBusinessNameTextField(String text) {
        businessNameTextField.setText(text);
    }
    
    public void setPercentageCommissionTextField(String text) {
        percentageCommissionTextField.setText(text);
    }
    
    public void addEditBusinessesTableModelListener(TableModelListener l) {
        DefaultTableModel model = (DefaultTableModel) this.editBusinessesTable.getModel();
        model.addTableModelListener(l);
    }
    
    public void addEditBusinessesTableMouseListener(MouseListener l) {
        this.editBusinessesTable.addMouseListener(l);
    }
    
    public String getEditBusinessTableIDAt(int row, int col) {
        String serialID = "";
        if (row >= 0 && col >= 0) {
            serialID = editBusinessesTable.getModel().getValueAt(row, col).toString();
        }
        return serialID;
    }

    public void clearBusinesses() {
        DefaultTableModel model = (DefaultTableModel) this.editBusinessesTable.getModel();
        model.setRowCount(0);
        editBusinessesTable.clearSelection();
        editBusinessesTable.revalidate();
        editBusinessesTable.repaint();
    }

    public void addBusiness(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.editBusinessesTable.getModel();
        model.addRow(row);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBusinessBackButton;
    private javax.swing.JButton addBusinessButton;
    private javax.swing.JPanel addBusinessJPanel;
    private javax.swing.JLabel businessNameLabel;
    private javax.swing.JTextField businessNameTextField;
    private javax.swing.JButton clearTextButton;
    private javax.swing.JButton deleteBusinessButton;
    private javax.swing.JButton editBusinessButton;
    private javax.swing.JButton editBusinessesBackButton;
    private javax.swing.JPanel editBusinessesJPanel;
    private javax.swing.JScrollPane editBusinessesScrollPane;
    private javax.swing.JTable editBusinessesTable;
    private javax.swing.JLabel manageBusinessLabel;
    private javax.swing.JTabbedPane manageBusinessTabbedPane;
    private javax.swing.JLabel percentageCommissionLabel;
    private javax.swing.JTextField percentageCommissionTextField;
    // End of variables declaration//GEN-END:variables
}
