/*
 * SBDNO - Small Business Delivery Note Organizer
 * 
 * Copyright (C) 2025 Adrián González Hermida
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package view.generateListingsView;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JFrame;

/**
 *
 * @author EVEN
 */
public class GenerateListingsFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GenerateListingsFrame.class.getName());

    /**
     * Creates new form GenerateListingFrame
     */
    public GenerateListingsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectDeliveryDateRangeLabel = new javax.swing.JLabel();
        selectDeliveryDateFromLabel = new javax.swing.JLabel();
        selectDeliveryDateUntilLabel = new javax.swing.JLabel();
        selectDeliveryFromDateButton = new javax.swing.JButton();
        selectDeliveryUntilDateButton = new javax.swing.JButton();
        generateListingLabel = new javax.swing.JLabel();
        generateListingButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        selectBusinessLabel = new javax.swing.JLabel();
        selectBusinessComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectDeliveryDateRangeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryDateRangeLabel.setText("Select Delivery Date Range:");

        selectDeliveryDateFromLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryDateFromLabel.setText("From:");

        selectDeliveryDateUntilLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryDateUntilLabel.setText("Until:");

        selectDeliveryFromDateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryFromDateButton.setText("Select Date");

        selectDeliveryUntilDateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryUntilDateButton.setText("Select Date");

        generateListingLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        generateListingLabel.setText("Generate Listing");

        generateListingButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generateListingButton.setText("Generate Listing");

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backButton.setText("Back");

        selectBusinessLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectBusinessLabel.setText("Select Business:");

        selectBusinessComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectBusinessComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateListingButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generateListingLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(selectDeliveryDateFromLabel)
                                        .addGap(69, 69, 69)
                                        .addComponent(selectDeliveryDateUntilLabel)
                                        .addGap(118, 118, 118))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(selectDeliveryDateRangeLabel)
                                        .addGap(51, 51, 51)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectBusinessLabel)
                                    .addComponent(selectBusinessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectDeliveryFromDateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectDeliveryUntilDateButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generateListingLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectDeliveryDateRangeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectDeliveryDateFromLabel)
                            .addComponent(selectDeliveryDateUntilLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectBusinessLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectBusinessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDeliveryFromDateButton)
                    .addComponent(selectDeliveryUntilDateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateListingButton)
                    .addComponent(backButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDefaultCloseOperation(){
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void addGenerateListingButtonAL(ActionListener al){
        this.generateListingButton.addActionListener(al);
    }
    
    public void addBackButtonAL(ActionListener al){
        this.backButton.addActionListener(al);
    }
    
    public void addSelectDeliveryFromDateButtonAL(ActionListener al){
        this.selectDeliveryFromDateButton.addActionListener(al);
    }
    
    public void addSelectDeliveryUntilDateButtonAL(ActionListener al){
        this.selectDeliveryUntilDateButton.addActionListener(al);
    }
    
    public JComboBox getSelectBusinessComboBox(){
        return this.selectBusinessComboBox;
    }
    
    public void setSelectDeliveryFromDateText(String text){
        this.selectDeliveryFromDateButton.setText(text);
    }
    
    public void setSelectDeliveryUntilDateText(String text){
        this.selectDeliveryUntilDateButton.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton generateListingButton;
    private javax.swing.JLabel generateListingLabel;
    private javax.swing.JComboBox<String> selectBusinessComboBox;
    private javax.swing.JLabel selectBusinessLabel;
    private javax.swing.JLabel selectDeliveryDateFromLabel;
    private javax.swing.JLabel selectDeliveryDateRangeLabel;
    private javax.swing.JLabel selectDeliveryDateUntilLabel;
    private javax.swing.JButton selectDeliveryFromDateButton;
    private javax.swing.JButton selectDeliveryUntilDateButton;
    // End of variables declaration//GEN-END:variables
}
