/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.manageStoresView;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

public class ManageStoresFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageStoresFrame.class.getName());

    /**
     * Creates new form ManageStoresFrame
     */
    public ManageStoresFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageStoresLabel = new javax.swing.JLabel();
        manageStoresTabbedPane = new javax.swing.JTabbedPane();
        addStoreJPanel = new javax.swing.JPanel();
        selectBusinessNameLabel = new javax.swing.JLabel();
        storeNameLabel = new javax.swing.JLabel();
        storeNameTextField = new javax.swing.JTextField();
        clearTextButton = new javax.swing.JButton();
        addStoreButton = new javax.swing.JButton();
        addStoreBackButton = new javax.swing.JButton();
        selectBusinessComboBox = new javax.swing.JComboBox<>();
        editStoresJPanel = new javax.swing.JPanel();
        editStoresScrollPane = new javax.swing.JScrollPane();
        editStoresTable = new javax.swing.JTable();
        editStoreButton = new javax.swing.JButton();
        deleteStoreButton = new javax.swing.JButton();
        editStoresBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageStoresLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageStoresLabel.setText("Manage Stores");

        manageStoresTabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        selectBusinessNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectBusinessNameLabel.setText("Select Business:");

        storeNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        storeNameLabel.setText("Store Name:");

        storeNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        clearTextButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearTextButton.setText("Clear Text");

        addStoreButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addStoreButton.setText("Add Store");

        addStoreBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addStoreBackButton.setText("Back");

        selectBusinessComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectBusinessComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout addStoreJPanelLayout = new javax.swing.GroupLayout(addStoreJPanel);
        addStoreJPanel.setLayout(addStoreJPanelLayout);
        addStoreJPanelLayout.setHorizontalGroup(
            addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStoreJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStoreBackButton)
                    .addGroup(addStoreJPanelLayout.createSequentialGroup()
                        .addComponent(selectBusinessNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectBusinessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addStoreJPanelLayout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addComponent(clearTextButton)
                        .addGap(18, 18, 18)
                        .addComponent(addStoreButton))
                    .addGroup(addStoreJPanelLayout.createSequentialGroup()
                        .addComponent(storeNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(storeNameTextField)))
                .addContainerGap())
        );
        addStoreJPanelLayout.setVerticalGroup(
            addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addStoreJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectBusinessNameLabel)
                    .addComponent(storeNameLabel)
                    .addComponent(storeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectBusinessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(addStoreJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearTextButton)
                    .addComponent(addStoreButton)
                    .addComponent(addStoreBackButton))
                .addContainerGap())
        );

        manageStoresTabbedPane.addTab("Add Store", addStoreJPanel);

        editStoresTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editStoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Business ID", "Store ID", "Business Name", "Store Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        editStoresScrollPane.setViewportView(editStoresTable);

        editStoreButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editStoreButton.setText("Edit Store");

        deleteStoreButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteStoreButton.setText("Delete Store");

        editStoresBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editStoresBackButton.setText("Back");

        javax.swing.GroupLayout editStoresJPanelLayout = new javax.swing.GroupLayout(editStoresJPanel);
        editStoresJPanel.setLayout(editStoresJPanelLayout);
        editStoresJPanelLayout.setHorizontalGroup(
            editStoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStoresJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editStoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editStoresScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editStoresJPanelLayout.createSequentialGroup()
                        .addComponent(editStoresBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteStoreButton)
                        .addGap(18, 18, 18)
                        .addComponent(editStoreButton)))
                .addContainerGap())
        );
        editStoresJPanelLayout.setVerticalGroup(
            editStoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editStoresJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editStoresScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(editStoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editStoreButton)
                    .addComponent(deleteStoreButton)
                    .addComponent(editStoresBackButton))
                .addContainerGap())
        );

        manageStoresTabbedPane.addTab("Edit Stores", editStoresJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageStoresTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageStoresLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageStoresLabel)
                .addGap(12, 12, 12)
                .addComponent(manageStoresTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setSetDefaultCloseOperation(){
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void addAddStoreBackButtonAL(ActionListener al){
        this.addStoreBackButton.addActionListener(al);
    }
    
    public void addEditStoresBackButtonAL(ActionListener al){
        this.editStoresBackButton.addActionListener(al);
    }
    
    public void addClearTextButtonAL(ActionListener al){
        this.clearTextButton.addActionListener(al);
    }
    
    public void addAddStoreButtonAL(ActionListener al){
        this.addStoreButton.addActionListener(al);
    }
    
    public void addEditStoreButtonAL(ActionListener al){
        this.editStoreButton.addActionListener(al);
    }
    
    public void addDeleteStoreButtonAL(ActionListener al){
        this.deleteStoreButton.addActionListener(al);
    }
    
    public String getStoreNameTextFieldText(){
        return this.storeNameTextField.getText();
    }
    
    public void setStoreNameTextFieldText(String text){
        this.storeNameTextField.setText(text);
    }
    
    public JTable getEditStoresTable() {
        return this.editStoresTable;
    }
    
    public JComboBox getSelectBusinessComboBox(){
        return this.selectBusinessComboBox;
    }
    
    public void setSelectBusinessComboBoxModel(ComboBoxModel<String> cbm){
        this.selectBusinessComboBox.setModel(cbm);
    }
    
    public void addEditStoresTableModelListener(TableModelListener l) {
        DefaultTableModel model = (DefaultTableModel) this.editStoresTable.getModel();
        model.addTableModelListener(l);
    }
    
    public void addEditStoresTableMouseListener(MouseListener l) {
        this.editStoresTable.addMouseListener(l);
    }
    
    public String getEditStoresTableIDAt(int row, int col) {
        String id = "";
        if (row >= 0 && col >= 0) {
            id = editStoresTable.getModel().getValueAt(row, col).toString();
        }
        return id;
    }
    
    public void clearStores() {
        DefaultTableModel model = (DefaultTableModel) this.editStoresTable.getModel();
        model.setRowCount(0);
        editStoresTable.clearSelection();
        editStoresTable.revalidate();
        editStoresTable.repaint();
    }

    public void addBusiness(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.editStoresTable.getModel();
        model.addRow(row);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStoreBackButton;
    private javax.swing.JButton addStoreButton;
    private javax.swing.JPanel addStoreJPanel;
    private javax.swing.JButton clearTextButton;
    private javax.swing.JButton deleteStoreButton;
    private javax.swing.JButton editStoreButton;
    private javax.swing.JButton editStoresBackButton;
    private javax.swing.JPanel editStoresJPanel;
    private javax.swing.JScrollPane editStoresScrollPane;
    private javax.swing.JTable editStoresTable;
    private javax.swing.JLabel manageStoresLabel;
    private javax.swing.JTabbedPane manageStoresTabbedPane;
    private javax.swing.JComboBox<String> selectBusinessComboBox;
    private javax.swing.JLabel selectBusinessNameLabel;
    private javax.swing.JLabel storeNameLabel;
    private javax.swing.JTextField storeNameTextField;
    // End of variables declaration//GEN-END:variables
}
