/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.manageSellersView.editSellerView;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;

/**
 *
 * @author EVEN
 */
public class EditSellerDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditSellerDialog.class.getName());

    /**
     * Creates new form EditSellerDialog
     */
    public EditSellerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        sellerNameLabel = new javax.swing.JLabel();
        sellerNameTextField = new javax.swing.JTextField();
        selectBusinessLabel = new javax.swing.JLabel();
        selectStoreComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        acceptButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acceptButton.setText("Accept");

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");

        sellerNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sellerNameLabel.setText("Seller Name:");

        sellerNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        selectBusinessLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectBusinessLabel.setText("Select Store:");

        selectStoreComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sellerNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sellerNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acceptButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectBusinessLabel)
                        .addGap(18, 18, 18)
                        .addComponent(selectStoreComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellerNameLabel)
                    .addComponent(sellerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectBusinessLabel)
                    .addComponent(selectStoreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addAcceptButtonAL(ActionListener al){
        this.acceptButton.addActionListener(al);
    }
    
    public void addCancelButtonAL(ActionListener al){
        this.cancelButton.addActionListener(al);
    }
    
    public JComboBox getSelectStoreComboBox(){
        return this.selectStoreComboBox;
    }
    
    public String getSellerNameTextFieldText(){
        return this.sellerNameTextField.getText();
    }
    
    public void setSellerNameTextFieldText(String text){
        this.sellerNameTextField.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel selectBusinessLabel;
    private javax.swing.JComboBox<String> selectStoreComboBox;
    private javax.swing.JLabel sellerNameLabel;
    private javax.swing.JTextField sellerNameTextField;
    // End of variables declaration//GEN-END:variables
}
