/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.manageEmployeesView;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EVEN
 */
public class ManageEmployeesFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageEmployeesFrame.class.getName());

    /**
     * Creates new form ManageWorkersFrame
     */
    public ManageEmployeesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEmployeesLabel = new javax.swing.JLabel();
        manageEmployeeTabbedPane = new javax.swing.JTabbedPane();
        addBusinessJPanel = new javax.swing.JPanel();
        employeeNameLabel = new javax.swing.JLabel();
        employeeNameTextField = new javax.swing.JTextField();
        employeeStatusLabel = new javax.swing.JLabel();
        clearTextButton = new javax.swing.JButton();
        addEmployeeButton = new javax.swing.JButton();
        addEmployeeBackButton = new javax.swing.JButton();
        employeeStatusComboBox = new javax.swing.JComboBox<>();
        editBusinessesJPanel = new javax.swing.JPanel();
        editBusinessesScrollPane = new javax.swing.JScrollPane();
        editEmployeeTable = new javax.swing.JTable();
        editEmployeeButton = new javax.swing.JButton();
        deleteEmployeeButton = new javax.swing.JButton();
        editEmployeeBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageEmployeesLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageEmployeesLabel.setText("Manage Employees");

        manageEmployeeTabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        employeeNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employeeNameLabel.setText("Employee Name:");

        employeeNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        employeeStatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employeeStatusLabel.setText("Employee Status:");

        clearTextButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearTextButton.setText("Clear Text");

        addEmployeeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addEmployeeButton.setText("Add Employee");

        addEmployeeBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addEmployeeBackButton.setText("Back");

        employeeStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout addBusinessJPanelLayout = new javax.swing.GroupLayout(addBusinessJPanel);
        addBusinessJPanel.setLayout(addBusinessJPanelLayout);
        addBusinessJPanelLayout.setHorizontalGroup(
            addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                        .addComponent(employeeNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addEmployeeBackButton))
                .addGap(18, 18, 18)
                .addGroup(addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clearTextButton)
                        .addGap(18, 18, 18)
                        .addComponent(addEmployeeButton))
                    .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                        .addComponent(employeeStatusLabel)
                        .addGap(18, 18, 18)
                        .addComponent(employeeStatusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addBusinessJPanelLayout.setVerticalGroup(
            addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBusinessJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeNameLabel)
                    .addComponent(employeeStatusLabel)
                    .addComponent(employeeStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(addBusinessJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearTextButton)
                    .addComponent(addEmployeeButton)
                    .addComponent(addEmployeeBackButton))
                .addContainerGap())
        );

        manageEmployeeTabbedPane.addTab("Add Employees", addBusinessJPanel);

        editEmployeeTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editEmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Employee ID", "Employee Name", " Employee State"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        editBusinessesScrollPane.setViewportView(editEmployeeTable);

        editEmployeeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editEmployeeButton.setText("Edit Employee");

        deleteEmployeeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteEmployeeButton.setText("Delete Employee");

        editEmployeeBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editEmployeeBackButton.setText("Back");

        javax.swing.GroupLayout editBusinessesJPanelLayout = new javax.swing.GroupLayout(editBusinessesJPanel);
        editBusinessesJPanel.setLayout(editBusinessesJPanelLayout);
        editBusinessesJPanelLayout.setHorizontalGroup(
            editBusinessesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editBusinessesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editBusinessesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editBusinessesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editBusinessesJPanelLayout.createSequentialGroup()
                        .addComponent(editEmployeeBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteEmployeeButton)
                        .addGap(18, 18, 18)
                        .addComponent(editEmployeeButton)))
                .addContainerGap())
        );
        editBusinessesJPanelLayout.setVerticalGroup(
            editBusinessesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editBusinessesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editBusinessesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(editBusinessesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEmployeeButton)
                    .addComponent(deleteEmployeeButton)
                    .addComponent(editEmployeeBackButton))
                .addContainerGap())
        );

        manageEmployeeTabbedPane.addTab("Edit Employees", editBusinessesJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageEmployeeTabbedPane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageEmployeesLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageEmployeesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageEmployeeTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDefaultCloseOperation(){
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public JTable getEditEmployeeTable() {
        return this.editEmployeeTable;
    }
    
    public String getEmployeeNameTextField() {
        return this.employeeNameTextField.getText();
    }
    
    public JComboBox getEmployeeStatusComboBox(){
        return this.employeeStatusComboBox;
    }

    public void addAddEmployeeButtonAL(ActionListener al) {
        addEmployeeButton.addActionListener(al);
    }

    public void addClearTextButtonAL(ActionListener al) {
        clearTextButton.addActionListener(al);
    }
    
    public void addAddEmployeeBackButtonAL(ActionListener al) {
        addEmployeeBackButton.addActionListener(al);
    }
    
    public void addEditEmployeeBackButtonAL(ActionListener al) {
        editEmployeeBackButton.addActionListener(al);
    }
    
    public void addDeleteEmployeeButtonAL(ActionListener al) {
        deleteEmployeeButton.addActionListener(al);
    }

    public void addEditEmployeeButtonAL(ActionListener al) {
        editEmployeeButton.addActionListener(al);
    }

    public void setEmployeeNameTextField(String text) {
        employeeNameTextField.setText(text);
    }
    
    public void addEditEmployeeTableModelListener(TableModelListener l) {
        DefaultTableModel model = (DefaultTableModel) this.editEmployeeTable.getModel();
        model.addTableModelListener(l);
    }
    
    public void addEditEmployeeTableMouseListener(MouseListener l) {
        this.editEmployeeTable.addMouseListener(l);
    }
    
    public String getEditEmployeeTableIDAt(int row, int col) {
        String id = "";
        if (row >= 0 && col >= 0) {
            id = editEmployeeTable.getModel().getValueAt(row, col).toString();
        }
        return id;
    }

    public void clearEmployees() {
        DefaultTableModel model = (DefaultTableModel) this.editEmployeeTable.getModel();
        model.setRowCount(0);
        editEmployeeTable.clearSelection();
        editEmployeeTable.revalidate();
        editEmployeeTable.repaint();
    }

    public void addEmployee(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.editEmployeeTable.getModel();
        model.addRow(row);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addBusinessJPanel;
    private javax.swing.JButton addEmployeeBackButton;
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JButton clearTextButton;
    private javax.swing.JButton deleteEmployeeButton;
    private javax.swing.JPanel editBusinessesJPanel;
    private javax.swing.JScrollPane editBusinessesScrollPane;
    private javax.swing.JButton editEmployeeBackButton;
    private javax.swing.JButton editEmployeeButton;
    private javax.swing.JTable editEmployeeTable;
    private javax.swing.JLabel employeeNameLabel;
    private javax.swing.JTextField employeeNameTextField;
    private javax.swing.JComboBox<String> employeeStatusComboBox;
    private javax.swing.JLabel employeeStatusLabel;
    private javax.swing.JTabbedPane manageEmployeeTabbedPane;
    private javax.swing.JLabel manageEmployeesLabel;
    // End of variables declaration//GEN-END:variables
}
