/*
 * SBDNO - Small Business Delivery Note Organizer
 * 
 * Copyright (C) 2025 Adrián González Hermida
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package view.manageClientsView;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EVEN
 */
public class ManageClientsFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageClientsFrame.class.getName());

    /**
     * Creates new form ManageClientsFrame
     */
    public ManageClientsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageClientsLabel = new javax.swing.JLabel();
        manageClientsTabbedPane = new javax.swing.JTabbedPane();
        addClientJPanel = new javax.swing.JPanel();
        clientNameLabel = new javax.swing.JLabel();
        clientNameTextField = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        clearTextButton = new javax.swing.JButton();
        addClientButton = new javax.swing.JButton();
        addClientBackButton = new javax.swing.JButton();
        editClientsJPanel = new javax.swing.JPanel();
        editClientsScrollPane = new javax.swing.JScrollPane();
        editClientsTable = new javax.swing.JTable();
        editClientButton = new javax.swing.JButton();
        deleteClientButton = new javax.swing.JButton();
        editClientsBackButton = new javax.swing.JButton();
        searchClientsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageClientsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        manageClientsLabel.setText("Manage Clients");

        manageClientsTabbedPane.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        clientNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientNameLabel.setText("Name:");

        clientNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        phoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneNumberLabel.setText("Phone Number:");

        phoneNumberTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        clearTextButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearTextButton.setText("Clear Text");

        addClientButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addClientButton.setText("Add Client");

        addClientBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addClientBackButton.setText("Back");

        javax.swing.GroupLayout addClientJPanelLayout = new javax.swing.GroupLayout(addClientJPanel);
        addClientJPanel.setLayout(addClientJPanelLayout);
        addClientJPanelLayout.setHorizontalGroup(
            addClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addClientJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addClientJPanelLayout.createSequentialGroup()
                        .addComponent(clientNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addClientBackButton))
                .addGap(18, 18, 18)
                .addGroup(addClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addClientJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clearTextButton)
                        .addGap(18, 18, 18)
                        .addComponent(addClientButton))
                    .addGroup(addClientJPanelLayout.createSequentialGroup()
                        .addComponent(phoneNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNumberTextField)))
                .addContainerGap())
        );
        addClientJPanelLayout.setVerticalGroup(
            addClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addClientJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientNameLabel)
                    .addComponent(phoneNumberLabel)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(addClientJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearTextButton)
                    .addComponent(addClientButton)
                    .addComponent(addClientBackButton))
                .addContainerGap())
        );

        manageClientsTabbedPane.addTab("Add Client", addClientJPanel);

        editClientsTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editClientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Client ID", "Client Name", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        editClientsScrollPane.setViewportView(editClientsTable);

        editClientButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editClientButton.setText("Edit Client");

        deleteClientButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteClientButton.setText("Delete Client");

        editClientsBackButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editClientsBackButton.setText("Back");

        searchClientsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchClientsButton.setText("Search");

        javax.swing.GroupLayout editClientsJPanelLayout = new javax.swing.GroupLayout(editClientsJPanel);
        editClientsJPanel.setLayout(editClientsJPanelLayout);
        editClientsJPanelLayout.setHorizontalGroup(
            editClientsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editClientsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editClientsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editClientsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editClientsJPanelLayout.createSequentialGroup()
                        .addComponent(editClientsBackButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchClientsButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteClientButton)
                        .addGap(18, 18, 18)
                        .addComponent(editClientButton)))
                .addContainerGap())
        );
        editClientsJPanelLayout.setVerticalGroup(
            editClientsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editClientsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editClientsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(editClientsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editClientButton)
                    .addComponent(deleteClientButton)
                    .addComponent(editClientsBackButton)
                    .addComponent(searchClientsButton))
                .addContainerGap())
        );

        manageClientsTabbedPane.addTab("Edit Clients", editClientsJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageClientsTabbedPane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageClientsLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageClientsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageClientsTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setSetDefaultCloseOperation(){
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public JTable getEditClientsJTable(){
        return this.editClientsTable;
    }
    
    public String getClientNameTextFieldText(){
        return this.clientNameTextField.getText();
    }
    
    public String getPhoneNumberTextFieldText(){
        return this.phoneNumberTextField.getText();
    }
    
    public void setClientNameTextFieldText(String text){
        this.clientNameTextField.setText(text);
    }
    
    public void setPhoneNumberTextFieldText(String text){
        this.phoneNumberTextField.setText(text);
    }
    
    public void addAddClientBackButtonAL(ActionListener al){
        this.addClientBackButton.addActionListener(al);
    }
    
    public void addEditClientBackButtonAL(ActionListener al){
        this.editClientsBackButton.addActionListener(al);
    }
    
    public void addClearTextButtonAL(ActionListener al){
        this.clearTextButton.addActionListener(al);
    }
    
    public void addAddClientButtonAL(ActionListener al){
        this.addClientButton.addActionListener(al);
    }
    
    public void addDeleteClientButtonAL(ActionListener al){
        this.deleteClientButton.addActionListener(al);
    }
    
    public void addEditClientButtonAL(ActionListener al){
        this.editClientButton.addActionListener(al);
    }
    
    public void addSearchClientsButtonAL(ActionListener al ){
        this.searchClientsButton.addActionListener(al);
    }
    
    public void addEditClientsTableModelListener(TableModelListener l) {
        DefaultTableModel model = (DefaultTableModel) this.editClientsTable.getModel();
        model.addTableModelListener(l);
    }
    
    public void addEditClientsTableMouseListener(MouseListener l) {
        this.editClientsTable.addMouseListener(l);
    }
    
    public String getEditClientsTableIDAt(int row, int col) {
        String id = "";
        if (row >= 0 && col >= 0) {
            id = editClientsTable.getModel().getValueAt(row, col).toString();
        }
        return id;
    }

    public void clearClients() {
        DefaultTableModel model = (DefaultTableModel) this.editClientsTable.getModel();
        model.setRowCount(0);
        editClientsTable.clearSelection();
        editClientsTable.revalidate();
        editClientsTable.repaint();
    }

    public void addClient(Vector row) {
        DefaultTableModel model = (DefaultTableModel) this.editClientsTable.getModel();
        model.addRow(row);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClientBackButton;
    private javax.swing.JButton addClientButton;
    private javax.swing.JPanel addClientJPanel;
    private javax.swing.JButton clearTextButton;
    private javax.swing.JLabel clientNameLabel;
    private javax.swing.JTextField clientNameTextField;
    private javax.swing.JButton deleteClientButton;
    private javax.swing.JButton editClientButton;
    private javax.swing.JButton editClientsBackButton;
    private javax.swing.JPanel editClientsJPanel;
    private javax.swing.JScrollPane editClientsScrollPane;
    private javax.swing.JTable editClientsTable;
    private javax.swing.JLabel manageClientsLabel;
    private javax.swing.JTabbedPane manageClientsTabbedPane;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JButton searchClientsButton;
    // End of variables declaration//GEN-END:variables
}
