/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.searchManageDeliveryNoteView.filterDeliveryNotesView;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;

/**
 *
 * @author EVEN
 */
public class FilterDeliveryNotesDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FilterDeliveryNotesDialog.class.getName());

    /**
     * Creates new form FilterDeliveryNotesDialog
     */
    public FilterDeliveryNotesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientPhoneNumberLabel = new javax.swing.JLabel();
        selectAdditionFromDateButton = new javax.swing.JButton();
        selectTruckComboBox = new javax.swing.JComboBox<>();
        selectBusinessLabel = new javax.swing.JLabel();
        selectTruckLabel = new javax.swing.JLabel();
        selectBusinessComboBox = new javax.swing.JComboBox<>();
        selectStoreLabel = new javax.swing.JLabel();
        selectAmountRangeLabel = new javax.swing.JLabel();
        selectStoreComboBox = new javax.swing.JComboBox<>();
        selectSellerLabel = new javax.swing.JLabel();
        selectSellerComboBox = new javax.swing.JComboBox<>();
        filterDeliveryNotesButton = new javax.swing.JButton();
        clientNameLabel = new javax.swing.JLabel();
        clearEntriesButton = new javax.swing.JButton();
        filterDeliveryNoteLabel = new javax.swing.JLabel();
        clientNameTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        clientPhoneNumberTextField = new javax.swing.JTextField();
        selectAdditionDateRangeLabel = new javax.swing.JLabel();
        selectAdditionDateFromLabel = new javax.swing.JLabel();
        selectAdditionDateUntilLabel = new javax.swing.JLabel();
        selectAdditionUntilDateButton = new javax.swing.JButton();
        selectDeliveryDateRangeLabel = new javax.swing.JLabel();
        selectDeliveryDateFromLabel = new javax.swing.JLabel();
        selectDeliveryDateUntilLabel = new javax.swing.JLabel();
        selectDeliveryFromDateButton = new javax.swing.JButton();
        selectDeliveryUntilDateButton = new javax.swing.JButton();
        maxAmountLabel = new javax.swing.JLabel();
        minAmountLabel = new javax.swing.JLabel();
        minAmountTextField = new javax.swing.JTextField();
        maxAmountTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        clientPhoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientPhoneNumberLabel.setText("Client Phone Number:");

        selectAdditionFromDateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectAdditionFromDateButton.setText("Select Date");

        selectTruckComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectTruckComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectBusinessLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectBusinessLabel.setText("Select Business:");

        selectTruckLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectTruckLabel.setText("Select Truck:");

        selectBusinessComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectBusinessComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectStoreLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectStoreLabel.setText("Select Store:");

        selectAmountRangeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectAmountRangeLabel.setText("Select Amount Range:");

        selectStoreComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectStoreComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        selectSellerLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectSellerLabel.setText("Select Seller:");

        selectSellerComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectSellerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filterDeliveryNotesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filterDeliveryNotesButton.setText("Filter Delivery Notes");

        clientNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientNameLabel.setText("Client Name:");

        clearEntriesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearEntriesButton.setText("Clear Entries");

        filterDeliveryNoteLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        filterDeliveryNoteLabel.setText("Filter Delivery Notes");

        clientNameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backButton.setText("Back");

        clientPhoneNumberTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        selectAdditionDateRangeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectAdditionDateRangeLabel.setText("Select Addition Date Range:");

        selectAdditionDateFromLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectAdditionDateFromLabel.setText("From:");

        selectAdditionDateUntilLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectAdditionDateUntilLabel.setText("Until:");

        selectAdditionUntilDateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectAdditionUntilDateButton.setText("Select Date");

        selectDeliveryDateRangeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryDateRangeLabel.setText("Select Delivery Date Range:");

        selectDeliveryDateFromLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryDateFromLabel.setText("From:");

        selectDeliveryDateUntilLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryDateUntilLabel.setText("Until:");

        selectDeliveryFromDateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryFromDateButton.setText("Select Date");

        selectDeliveryUntilDateButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDeliveryUntilDateButton.setText("Select Date");

        maxAmountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maxAmountLabel.setText("Max:");

        minAmountLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        minAmountLabel.setText("Min:");

        minAmountTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        maxAmountTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectAdditionDateRangeLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectAdditionDateFromLabel)
                                .addGap(71, 71, 71)
                                .addComponent(selectAdditionDateUntilLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selectAdditionFromDateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectAdditionUntilDateButton))
                            .addComponent(backButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectDeliveryDateRangeLabel)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(selectDeliveryFromDateButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(selectDeliveryDateFromLabel)
                                                .addGap(70, 70, 70)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(selectDeliveryUntilDateButton)
                                            .addComponent(selectDeliveryDateUntilLabel))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(maxAmountLabel)
                                            .addComponent(selectAmountRangeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(maxAmountTextField)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearEntriesButton)
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientNameLabel)
                            .addComponent(clientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientPhoneNumberLabel)
                            .addComponent(clientPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(filterDeliveryNoteLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectBusinessLabel)
                            .addComponent(selectBusinessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectStoreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectStoreLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectSellerLabel)
                            .addComponent(selectSellerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectTruckComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectTruckLabel))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minAmountLabel)
                            .addComponent(minAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(filterDeliveryNotesButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterDeliveryNoteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectAdditionDateRangeLabel)
                    .addComponent(selectDeliveryDateRangeLabel)
                    .addComponent(selectAmountRangeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectAdditionDateFromLabel)
                    .addComponent(selectAdditionDateUntilLabel)
                    .addComponent(selectDeliveryDateFromLabel)
                    .addComponent(selectDeliveryDateUntilLabel)
                    .addComponent(maxAmountLabel)
                    .addComponent(minAmountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectAdditionFromDateButton)
                    .addComponent(selectAdditionUntilDateButton)
                    .addComponent(selectDeliveryFromDateButton)
                    .addComponent(selectDeliveryUntilDateButton)
                    .addComponent(minAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectBusinessLabel)
                    .addComponent(selectStoreLabel)
                    .addComponent(selectSellerLabel)
                    .addComponent(selectTruckLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectBusinessComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectStoreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectSellerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectTruckComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clientNameLabel)
                            .addComponent(clientPhoneNumberLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clientNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filterDeliveryNotesButton)
                            .addComponent(clearEntriesButton)
                            .addComponent(backButton))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void addClearEntriesButtonAL(ActionListener al){
        this.clearEntriesButton.addActionListener(al);
    }
    
    public void addFilterDeliveryNotesButtonAL(ActionListener al){
        this.filterDeliveryNotesButton.addActionListener(al);
    }
    
    public void addBackButtonAL(ActionListener al){
        this.backButton.addActionListener(al);
    }
    
    public void addSelectAdditionFromDateButtonAL(ActionListener al){
        this.selectAdditionFromDateButton.addActionListener(al);
    }
    
    public void addSelectAdditionUntilDateButtonAL(ActionListener al){
        this.selectAdditionUntilDateButton.addActionListener(al);
    }
    
    public void addSelectDeliveryFromDateButtonAL(ActionListener al){
        this.selectDeliveryFromDateButton.addActionListener(al);
    }
    
    public void addSelectDeliveryUntilDateButtonAL(ActionListener al){
        this.selectDeliveryUntilDateButton.addActionListener(al);
    }
    
    public void addSelectBusinesComboBoxAL(ActionListener al){
        this.selectBusinessComboBox.addActionListener(al);
    }
    
    public void addSelectStoreComboBoxAL(ActionListener al){
        this.selectStoreComboBox.addActionListener(al);
    }
    
    public void addSelectSellerComboBoxAL(ActionListener al){
        this.selectSellerComboBox.addActionListener(al);
    }
    
    public void addSelectTruckComboBoxAL(ActionListener al){
        this.selectTruckComboBox.addActionListener(al);
    }
    
    public JComboBox getSelectBusinessComboBox(){
        return this.selectBusinessComboBox;
    }
    
    public JComboBox getSelectStoreComboBox(){
        return this.selectStoreComboBox;
    }
    
    public JComboBox getSelectSellerComboBox(){
        return this.selectSellerComboBox;
    }
    
    public JComboBox getSelectTruckComboBox(){
        return this.selectTruckComboBox;
    }
    
    public String getMaxAmountTextFieldText(){
        return this.maxAmountTextField.getText();
    }
    
    public String getMinAmountTextFieldText(){
        return this.minAmountTextField.getText();
    }
    
    public String getClientNameTextFieldText(){
        return this.clientNameTextField.getText();
    }
    
    public String getClientPhoneNumberTextFieldText(){
        return this.clientPhoneNumberTextField.getText();
    }
    
    public void setMaxAmountTextFieldText(String text){
        this.maxAmountTextField.setText(text);
    }
    
    public void setMinAmountTextFieldText(String text){
        this.minAmountTextField.setText(text);
    }
    
    public void setClientNameTextFieldText(String text){
        this.clientNameTextField.setText(text);
    }
    
    public void setClientPhoneNumberTextFieldText(String text){
        this.clientPhoneNumberTextField.setText(text);
    }
    
    public void setSelectAdditionFromDateText(String text){
        this.selectAdditionFromDateButton.setText(text);
    }
    
    public void setSelectAdditionUntilDateText(String text){
        this.selectAdditionUntilDateButton.setText(text);
    }
    
    public void setSelectDeliveryFromDateText(String text){
        this.selectDeliveryFromDateButton.setText(text);
    }
    
    public void setSelectDeliveryUntilDateText(String text){
        this.selectDeliveryUntilDateButton.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearEntriesButton;
    private javax.swing.JLabel clientNameLabel;
    private javax.swing.JTextField clientNameTextField;
    private javax.swing.JLabel clientPhoneNumberLabel;
    private javax.swing.JTextField clientPhoneNumberTextField;
    private javax.swing.JLabel filterDeliveryNoteLabel;
    private javax.swing.JButton filterDeliveryNotesButton;
    private javax.swing.JLabel maxAmountLabel;
    private javax.swing.JTextField maxAmountTextField;
    private javax.swing.JLabel minAmountLabel;
    private javax.swing.JTextField minAmountTextField;
    private javax.swing.JLabel selectAdditionDateFromLabel;
    private javax.swing.JLabel selectAdditionDateRangeLabel;
    private javax.swing.JLabel selectAdditionDateUntilLabel;
    private javax.swing.JButton selectAdditionFromDateButton;
    private javax.swing.JButton selectAdditionUntilDateButton;
    private javax.swing.JLabel selectAmountRangeLabel;
    private javax.swing.JComboBox<String> selectBusinessComboBox;
    private javax.swing.JLabel selectBusinessLabel;
    private javax.swing.JLabel selectDeliveryDateFromLabel;
    private javax.swing.JLabel selectDeliveryDateRangeLabel;
    private javax.swing.JLabel selectDeliveryDateUntilLabel;
    private javax.swing.JButton selectDeliveryFromDateButton;
    private javax.swing.JButton selectDeliveryUntilDateButton;
    private javax.swing.JComboBox<String> selectSellerComboBox;
    private javax.swing.JLabel selectSellerLabel;
    private javax.swing.JComboBox<String> selectStoreComboBox;
    private javax.swing.JLabel selectStoreLabel;
    private javax.swing.JComboBox<String> selectTruckComboBox;
    private javax.swing.JLabel selectTruckLabel;
    // End of variables declaration//GEN-END:variables
}
