/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.configurationView;

import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JRadioButton;

/**
 *
 * @author EVEN
 */
public class ConfigurationFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfigurationFrame.class.getName());

    /**
     * Creates new form ConfigurationFrame
     */
    public ConfigurationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currencyTypeButtonGroup = new javax.swing.ButtonGroup();
        configurationLabel = new javax.swing.JLabel();
        selectCurrencyTypeLabel = new javax.swing.JLabel();
        euroRadioButton = new javax.swing.JRadioButton();
        poundRadioButton = new javax.swing.JRadioButton();
        dollarRadioButton = new javax.swing.JRadioButton();
        backButton = new javax.swing.JButton();
        confirmChangesButton = new javax.swing.JButton();
        selectDailyReportFolderLabel = new javax.swing.JLabel();
        selectDailyReportFolderButton = new javax.swing.JButton();
        selectListingsFolderLabel = new javax.swing.JLabel();
        selectListingFolderButton = new javax.swing.JButton();
        selectPersonalBusinessHeaderLabel = new javax.swing.JLabel();
        selectPersonalBusinessHeaderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        configurationLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        configurationLabel.setText("Configuration");

        selectCurrencyTypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectCurrencyTypeLabel.setText("Select Currency Type:");

        currencyTypeButtonGroup.add(euroRadioButton);
        euroRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        euroRadioButton.setText("€");

        currencyTypeButtonGroup.add(poundRadioButton);
        poundRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        poundRadioButton.setText("£");

        currencyTypeButtonGroup.add(dollarRadioButton);
        dollarRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dollarRadioButton.setText("$");

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backButton.setText("Back");

        confirmChangesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmChangesButton.setText("Confirm Changes");

        selectDailyReportFolderLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDailyReportFolderLabel.setText("Select Daily Report Folder:");

        selectDailyReportFolderButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDailyReportFolderButton.setText("Select Folder");

        selectListingsFolderLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectListingsFolderLabel.setText("Select Listing Folder:");

        selectListingFolderButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectListingFolderButton.setText("Select Folder");

        selectPersonalBusinessHeaderLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectPersonalBusinessHeaderLabel.setText("Select Personal Business Header:");

        selectPersonalBusinessHeaderButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectPersonalBusinessHeaderButton.setText("Select Image (950 x 560 px)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(confirmChangesButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(configurationLabel)
                            .addComponent(selectCurrencyTypeLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(euroRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(poundRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(dollarRadioButton))
                            .addComponent(selectDailyReportFolderLabel)
                            .addComponent(selectDailyReportFolderButton)
                            .addComponent(selectListingsFolderLabel)
                            .addComponent(selectListingFolderButton)
                            .addComponent(selectPersonalBusinessHeaderLabel)
                            .addComponent(selectPersonalBusinessHeaderButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(configurationLabel)
                .addGap(18, 18, 18)
                .addComponent(selectCurrencyTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(euroRadioButton)
                    .addComponent(poundRadioButton)
                    .addComponent(dollarRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectDailyReportFolderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectDailyReportFolderButton)
                .addGap(18, 18, 18)
                .addComponent(selectListingsFolderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectListingFolderButton)
                .addGap(18, 18, 18)
                .addComponent(selectPersonalBusinessHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectPersonalBusinessHeaderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(confirmChangesButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDefaultCloseOperation(){
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void addSelectDailyReportFolderButtonAL(ActionListener al){
        this.selectDailyReportFolderButton.addActionListener(al);
    }
    
    public void addSelectListingFolderButtonAL(ActionListener al){
        this.selectListingFolderButton.addActionListener(al);
    }
    
    public void addSelectPersonalBusinessHeaderButtonAL(ActionListener al){
        this.selectPersonalBusinessHeaderButton.addActionListener(al);
    }
    
    public void addConfirmChangesButtonAL(ActionListener al){
        this.confirmChangesButton.addActionListener(al);
    }
    
    public void addBackButtonAL(ActionListener al){
        this.backButton.addActionListener(al);
    }
    
    public JRadioButton getEuroRadioButton(){
        return this.euroRadioButton;
    }
    
    public JRadioButton getDollarRadioButton(){
        return this.dollarRadioButton;
    }
    
    public JRadioButton getPoundRadioButton(){
        return this.poundRadioButton;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel configurationLabel;
    private javax.swing.JButton confirmChangesButton;
    private javax.swing.ButtonGroup currencyTypeButtonGroup;
    private javax.swing.JRadioButton dollarRadioButton;
    private javax.swing.JRadioButton euroRadioButton;
    private javax.swing.JRadioButton poundRadioButton;
    private javax.swing.JLabel selectCurrencyTypeLabel;
    private javax.swing.JButton selectDailyReportFolderButton;
    private javax.swing.JLabel selectDailyReportFolderLabel;
    private javax.swing.JButton selectListingFolderButton;
    private javax.swing.JLabel selectListingsFolderLabel;
    private javax.swing.JButton selectPersonalBusinessHeaderButton;
    private javax.swing.JLabel selectPersonalBusinessHeaderLabel;
    // End of variables declaration//GEN-END:variables
}
